baseurl: "https://www.bufferbloat.net/projects/"
languageCode: "en-us"
title: "Bufferbloat.net"
disable404: false
canonifyURLs: true
relativeURLs: false
disableKinds: ["taxonomyTerm", "taxonomy"]

pluralizeListTitles: false
metadataFormat: yaml
params:
  stylesheets: [ "bootstrap.css", "font-awesome.css", "custom.css" ]
  recentTypes: [ "news", "wiki" ]
author:
  name: The Bufferbloat community
  email: bloat@lists.bufferbloat.net
blackfriday:
  plainIDAnchors: true
  sourceRelativeLinksEval: true
